name = "SophieFormalization"
defaultTargets = ["HolroydTalbot", "ErdosStraus", "CarmichaelTotientFunction", "TowerNonPrime", "DetermineAllPossibleValues"]

[[lean_lib]]
name = "HolroydTalbot"
roots = ["SophieFormalization.HolroydTalbot"]

[[lean_lib]]
name = "ErdosStraus"
roots = ["SophieFormalization.ErdosStraus"]

[[lean_lib]]
name = "CarmichaelTotientFunction"
roots = ["SophieFormalization.CarmichaelTotientFunction"]

[[lean_lib]]
name = "TowerNonPrime"
roots = ["SophieFormalization.TowerNonPrime"]

[[lean_lib]]
name = "DetermineAllPossibleValues"
roots = ["SophieFormalization.DetermineAllPossibleValues"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"
