name = "SophieFormalization"
defaultTargets = ["HolroydTalbot", "ErdosStraus", "CarmichaelTotientFunction"]

[[lean_lib]]
name = "HolroydTalbot"
roots = ["SophieFormalization.HolroydTalbot"]

[[lean_lib]]
name = "ErdosStraus"
roots = ["SophieFormalization.ErdosStraus"]

[[lean_lib]]
name = "CarmichaelTotientFunction"
roots = ["SophieFormalization.CarmichaelTotientFunction"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"
